language: objective-c
osx_image: xcode7.2

script:
  - make

env:
  - COCOAPODS_DISABLE_DETERMINISTIC_UUIDS=YES

xcode_workspace: Overcoat.xcworkspace
xcode_scheme:
  - OvercoatTests-OSX
  - OvercoatTests-iOS
  - OvercoatTests-tvOS
xcode_sdk:
  - macosx
  - iphonesimulator
  - appletvsimulator

matrix:
  exclude:
    - xcode_scheme: OvercoatApp-OSX
      xcode_sdk: iphonesimulator
    - xcode_scheme: OvercoatApp-OSX
      xcode_sdk: appletvsimulator

    - xcode_scheme: OvercoatApp-iOS
      xcode_sdk: macosx
    - xcode_scheme: OvercoatApp-iOS
      xcode_sdk: appletvsimulator

    - xcode_scheme: OvercoatApp-tvOS
      xcode_sdk: iphonesimulator
    - xcode_scheme: OvercoatApp-tvOS
      xcode_sdk: macosx
